export enum AvatarType {
    Man = 'male',
    Woman = 'girl',
    Bee = 'bee',
    Cat = 'cat',
    Dog = 'dog',
    Elephant = 'elephant',
    Flamingo = 'flamingo',
    Fox = 'fox',
    Giraffe = 'giraffe',
    Koala = 'koala',
    Leopard = 'leopard',
    Lion = 'lion',
    Monkey = 'monkey',
    Octopus = 'octopus',
    PandaBear = 'panda_bear',
    PolarBear = 'polar_bear',
    Rabbit = 'rabbit',
    Raccoon = 'raccoon',
    Rhino = 'rhino',
    Yak = 'yak',
    Empty = 'Empty',
    RobotA = 'robot_team_a',
    RobotB = 'robot_team_b',
}
